FlappyBirdv0 :
  env_id: FlappyBird-v0
  replay_buffer_size: 1000000
  mini_batch_size: 64
  epsilon_init: 1.0
  epsilon_final: 0.005
  epsilon_decay: 0.9995
  learning_rate: 0.0001
  time_to_sync: 10
  gamma: 0.99
  nums_episodes: 10000